### PR TITLE
Fix init from missing the last few candidates

### PR DESCRIPTION
**Pull request by danthegoodman**
In bash, `${#ARR}` returns the length of the string in the first slot.
'asciidoctorj' has a length of 12, which was working until more
candidates were added.

`${#ARR[*]}` is the correct way to return the length of an array in
bash. Thankfully, this works in ZSH as well.

This issue is preventing `vertx` from appearing on my path.

To demonstrate, you may run these commands in your shell:

```
$ echo ${GVM_CANDIDATES[*]}
asciidoctorj crash gaiden glide gradle grails griffon groovy groovyserv 
jbake jbossforge lazybones springboot vertx

$ echo ${#GVM_CANDIDATES}
12

$ echo ${#GVM_CANDIDATES[*]}
14
```

### CODE REVIEW

**Comment by danthegoodman** [comment]
Sure thing. I can give that a shot. Would you like the test in `src/test/steps/gvm/initialisation_steps.groovy` or a new `src/test/groovy/gvm/specs/InitialisationSpec.groovy`?

**Comment by marcoVermeulen** [comment]
Thanks! It sounds a little more like a Spock spec than a new feature, so `src/test/groovy/gvm/specs/InitialisationSpec.groovy` sounds like the better choice.

Would it be possible to test the current boundary conditions? Maybe have the exact candidate list that you were seeing problems with, and watching it fail first before we adding the fix.

**Comment by danthegoodman** [comment]
@marcoVermeulen I added the test. I wrote it on master, watched it fail, then committed it after my fix and watched it pass.

**Comment by marcoVermeulen** [comment]
Excellent work! Thanks!

**Pull request merged**
