### PR TITLE
Remote version is empty.

### PR DESCRIPTION
**Pull request by abcfy2**
Fix this issue:

```
The current version is , but you have 2.2.0.
```

### CODE REVIEW

**Comment by marcoVermeulen** [comment]
Sorry for not replying earlier. This changes the behaviour of GVM significantly. Since this radical change of behaviour was never discussed upfront (and also I don't agree with), I cannot merge the PR.

GVM functions much like a browser does, only in the shell. It makes regular calls back home for several reasons:

* checks if new broadcasts are available, a core part of gvm
* makes sure that you are still online, otherwise goes into offline mode
* checks daily to see if new updates are available

I think that removing these checks will break gvm in many other places since it is vital for it to remain connected to the internet. Once again, would you try using a browser while being offline? Well neither would you do so with GVM as much of it's logic lives on the serverside. It's not merely a script application, it is a client-server application.

Hope the explanation makes sense!

**Comment by abcfy2** [comment]
OK I know. I make these changes because connect to ``api.gvmtool.net`` is too slow from here, and also have some bugs(remote version is empty and update failed because download not complete, but the available gvm has been removed), often timeout or hang. I have to spend much time at every time to use gvm. So I want gvm will use offline resources as much as possible. It's unnecessary for gvm to connect internet at every time. The browser also holds local caches for speed up, isn't it?

But you are right. My changes will cause gvm never check update unless ``gvm selfupdate``. Maybe check update and broadcast in ``gvm-init.sh`` at every day is better.

Regards.

**Comment by marcoVermeulen** [comment]
Many of the issues you were experiencing have been fixed now. They are on
DEV and I'll be rolling them out shortly.

I have fixed remote version being blank (because of multiple shell issue).
Also, broadcasts are now very lightweight calls that only retrieve a
broadcast id, no longer the entire broadcast message.

Unfortunately we do need to ensure that you are online because most
commands in GVM rely on the internet. Here I refer to commands like list,
install, default, broadcast etc. which all rely on dynamic content from the
API. Also, browsers only cache static content.

**Comment by abcfy2** [comment]
Ah ha, it's right. I've already considered(Only not checking update and broadcast automatic).

    Usage: gvm <command> <candidate> [version]

``version`` is optional, if not provide, checking online. Otherwise check local if exits, find in local, use it, if not, connect the internet and download. This is my basic idea.

The candidate with specified version is static content. :)

**Pull request closed without merging**
